### PR TITLE
Add shortcut for yanking a directory path

### PR DESCRIPTION
**Pull request by tbrk**
Map 'yy' to yank the selected path.

### CODE REVIEW

**Comment by tpope** [comment]
I'm not sure we should provide a map like this at all, but if we do, it shouldn't override the ability to copy the filename on the current line.

**Comment by tbrk** [comment]
My initial use case was writing emails with mutt/vim and using vim-vinegar to browse for attachments and add an "Attach: " line in the header. Then I thought that maybe it's a useful idea in general. Maybe not!

I agree that the override is questionable. What about "yp" for "yank path"?

**Comment by tpope** [comment]
`yp` seems ok. I don't think `s:escaped()` has the right semantics for the implementation. You probably don't want literal `~/` paths in an `Attach:` header, no? Also joining on whitespace seems inappropriate. What *do* you want, ideally?

**Comment by tpope** [comment]
Actually let me tell you what I want, and see if that works for you:

* One line per file
* If no count is given, the single file is still yanked linewise by appending a newline
* Always use an absolute path

**Comment by tbrk** [comment]
That all sounds perfect.
* No literal `~/` paths.
* I'm not sure exactly what joining on whitespace means, but FWIW, I just checked in mutt and spaces in a path on an `Attach:` header work correctly (so does using a `\ `, but not using `"`s).
* Otherwise: yes, yes, and yes.

**Comment by tpope** [comment]
By "joining on whitespace" I was referring to *multiple* filenames. I assume mutt would want a separate `Attach:` header for each (which would fit with one file per line).

**Comment by tbrk** [comment]
Absolutely: one `Attach:` header is needed per file.

**Comment by tpope** [comment]
There was actually a much better map than `yp` hiding under our noses. :)

**Comment by tbrk** [comment]
That works great and the "y." map is perfect. Thank you!

**Pull request closed without merging**
