### PR TITLE
Update netrw_sort_sequence from 'suffixes'

### PR DESCRIPTION
**Pull request by kiryph**
in s:setup_vinegar() to reflect changes to suffixes
after vim startup

### CODE REVIEW

**Comment by tpope** [comment]
Can you confirm this works the first time you open a netrw buffer? I would expect the `FileType` event to be too late (but can't really test at the moment).

**Comment by kiryph** [comment]
Yes, I can confirm, that the sorting is already correct when I open the first time a netrw buffer.

vim help says following (note last sentence):

```
							*:filetype* *:filet*
To enable file type detection, use this command in your vimrc: >
	:filetype on
Each time a new or existing file is edited, Vim will try to recognize the type
of the file and set the 'filetype' option.  This will trigger the FileType
event, which can be used to set the syntax highlighting, set options, etc.
```
This does sound like it is intended that the event is triggered before syntax highlighting is done.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 17 2016 05:04:31)
MacOS X (unix) version
Included patches: 1-1831

**Comment by kiryph** [comment]
@tpope I have a quick question: Why did this not make it into version 1.0 of vinegar?

**Comment by kiryph** [comment]
I am especially interested for LaTeX projects. I am using the plugin vimtex which adjusts suffixes for LaTeX files
https://github.com/lervag/vimtex/blob/203d52f788dc9febece89375bc51520c4c32a68e/autoload/vimtex.vim#L309-L332.

There are so many generated files in a folder containing a LaTeX project that I really like the sorting based on suffixes done by vinegar.

**Comment by tpope** [comment]
Because the issue tracker is full of Netrw bugs and hidden buffer whinging and it got lost in the noise. At any rate this is a nontrivial change I wouldn't want to merge 2 minutes before cutting a release.

But I guess now is fine, if you fix the conflicts.

**Comment by tpope** [comment]
P.S. it doesn't affect my decision but vimtex setting a global option on a per buffer basis is messed up.

**Comment by kiryph** [comment]
I agree with you that setting a global option in a filetype plugin is suboptimal. The sorting behavior changes dependent on which filetypes you have opened in vim. This can feel unpredictable for the uninformed.

However, this is not only an issue of vimtex and found already its way into `$VIMRUNTIME/ftplugin/java.vim` and `$VIMRUNTIME/ftplugin/matlab.vim`.
I would also argue that if a user changes `suffixes` manually in a session, it would be nice if this could be taken into account.
Finally, I think LaTeX is a special case: there are so many extensions which can occur in a LaTeX project for generated files, I would not add all possible ones to `suffixes` on vim startup. There are most likely colllisions with other languages where an extension can play a different role (see following link if you are not familiar with LaTeX and the never ending list of file extensions in use: https://tex.stackexchange.com/q/7770/file-extensions-related-to-latex-etc).

### Regarding the Pull Request
Instead of moving the line into `s:setup_vinegar()`, it would also be possible to use the event `OptionSet`. This has been added in patch 7.4.786 (17 Jul 2015) with some fixes later on
```viml
augroup update_netrw_sort_squence
  autocmd!
  " if has('patch-7.4.786')
    autocmd OptionSet suffixes
            \ let g:netrw_sort_sequence = '[\/]$,*,\%(' . join(map(split(&suffixes, ','), 'escape(v:val, ".*$~")'), '\|') . '\)[*@]\=$'
    " endif
augroup END
```

Changelog of vim:
```
Patch 7.4.786
Problem:    It is not possible for a plugin to adjust to a changed setting.
Solution:   Add the OptionSet autocommand event. (Christian Brabandt)

Patch 7.4.888
Problem:    The OptionSet autocommands are not triggered from setwinvar().
Solution:   Do not use switch_win() when not needed. (Hirohito Higashi)

Patch 8.0.0676:
Problem:    Crash when closing the quickfix window in a FileType autocommand
            that triggers when the quickfix window is opened.
Solution:   Save the new value before triggering the OptionSet autocommand.
            Add the "starting" flag to test_override() to make the text work.

Patch 8.0.0736:
Problem:    The OptionSet autocommand event is not triggered when entering
            diff mode.
Solution:   use set_option_value() instead of setting the option directly.
            Change the tests from old to new style. (Christian Brabandt)

Patch 8.0.0974
Problem:    Resetting a string option does not trigger OptionSet. (Rick Howe)
Solution:   Set the origval.
```

**Comment by kiryph** [comment]
I was not able to squash the commits. Therefore I have created a new PR #94 with a single commit

**Pull request closed without merging**
